apiVersion: apps/v1
kind: Deployment
metadata:
  name: plagiarism-api
  namespace: plagiarism
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plagiarism-api
  template:
    metadata:
      labels:
        app: plagiarism-api
    spec:
      serviceAccountName: plagiarism-api-sa
      containers:
        - name: plagiarism-api
          image: baoghetcode/plagiarism-api:postgres-v1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000

          env:
            # PlagiarismCheck CRD
            - name: PLAGIARISM_NAMESPACE
              value: plagiarism
            - name: PLAGIARISM_CRD_GROUP
              value: plagiarism.io
            - name: PLAGIARISM_CRD_VERSION
              value: v1
            - name: PLAGIARISM_CRD_PLURAL
              value: plagiarismchecks
            - name: PLAGIARISM_CRD_KIND
              value: PlagiarismCheck

            # Result database:
            # Lưu metadata, trạng thái và kết quả plagiarism.
            # topic_id chỉ để hiển thị/dev.
            # subject_id được worker dùng để lọc MinHash.
            - name: RESULT_POSTGRES_DSN
              value: postgresql://plagiarism_user:postgres@postgresdb.streaming.svc.cluster.local:5432/plagiarism_system

            # MinIO
            - name: MINIO_ENDPOINT
              value: minio-svc-private.storage.svc.cluster.local:9000
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: secret-key
            - name: MINIO_SECURE
              value: "false"
            - name: VALIDATE_MINIO_OBJECT
              value: "true"

          readinessProbe:
            httpGet:
              path: /docs
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /docs
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: plagiarism-api-svc
  namespace: plagiarism
spec:
  type: NodePort
  selector:
    app: plagiarism-api
  ports:
    - name: http
      port: 8000
      targetPort: http
      nodePort: 30080